name: Bullhorn CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: Lint, build and test bullhorn
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        python-version:
          - "3.10"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.5.3

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint backend
        run: black . --check

      - name: Run Django tests
        run: coverage run -m pytest

      - name: Print test coverage report
        run: coverage report -m
